//Get All Users
export const ADMIN_GET_USERS_REQUEST = "ADMIN_GET_USERS_REQUEST";
export const ADMIN_GET_USERS_SUCCESS = "ADMIN_GET_USERS_SUCCESS";
export const ADMIN_GET_USERS_FAILURE = "ADMIN_GET_USERS_FAILURE";
//Get All Products
export const ADMIN_GET_PRODUCTS_REQUEST = "ADMIN_GET_PRODUCTS_REQUEST";
export const ADMIN_GET_PRODUCTS_SUCCESS = "ADMIN_GET_PRODUCTS_SUCCESS";
export const ADMIN_GET_PRODUCTS_FAILURE = "ADMIN_GET_PRODUCTS_FAILURE";
//Add  Products
export const ADMIN_ADD_PRODUCT_REQUEST = "ADMIN_ADD_PRODUCT_REQUEST";
export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS";
export const ADMIN_ADD_PRODUCT_FAILURE = "ADMIN_GET_PRODUCT_FAILURE";
//Get All Orders
export const ADMIN_GET_ORDERS_REQUEST = "ADMIN_GET_ORDERS_REQUEST";
export const ADMIN_GET_ORDERS_SUCCESS = "ADMIN_GET_ORDERS_SUCCESS";
export const ADMIN_GET_ORDERS_FAILURE = "ADMIN_GET_ORDERS_FAILURE";
//Delete Products
export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE";
