//Add to cart
export const ADD_TO_CART_ITEM_REQUEST = "ADD_TO_CART_ITEM_REQUEST";
export const ADD_TO_CART_ITEM_SUCCESS = "ADD_TO_CART_ITEM_SUCCESS";
export const ADD_TO_CART_ITEM_FAILURE = "ADD_TO_CART_ITEM_FAILURE";
//Delete From cart
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";
//Change quantity of item in cart
export const UPADTE_CART_ITEM_REQUEST = "UPADTE_CART_ITEM_REQUEST";
export const UPADTE_CART_ITEM_SUCCESS = "UPADTE_CART_ITEM_SUCCESS";
export const UPADTE_CART_ITEM_FAILURE = "UPADTE_CART_ITEM_FAILURE";
//Get Cart Item
export const GET_CART_ITEM_REQUEST = "GET_CART_ITEM_REQUEST";
export const GET_CART_ITEM_SUCCESS = "GET_CART_ITEM_SUCCESS";
export const GET_CART_ITEM_FAILURE = "GET_CART_ITEM_FAILURE";

//
