//Add to cart
export const GET_ORDER_ITEMS_REQUEST = "GET_ORDER_ITEMS_REQUEST";
export const GET_ORDER_ITEMS_SUCCESS = "GET_ORDER_ITEMS_SUCCESS";
export const GET_ORDER_ITEMS_FAILURE = "GET_ORDER_ITEMS_FAILURE";
