//Add to Wishlist
export const ADD_WISHLIST_REQUEST = " ADD_WISHLIST_REQUEST";
export const ADD_WISHLIST_SUCCESS = " ADD_WISHLIST_SUCCESS";
export const ADD_WISHLIST_FAILURE = " ADD_WISHLIST_FAILURE";
//Add to Wishlist
export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAILURE = "GET_WISHLIST_FAILURE";
