export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

//one product dettails
export const ONE_PRODUCT_REQUEST = "ONE_PRODUCT_REQUEST";
export const ONE_PRODUCT_SUCCESS = "ONE_PRODUCT_SUCCESS";
export const ONE_PRODUCT_FAIL = "ONE_PRODUCT_FAIL";
