//User profile Details
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";
//User profile Details
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
//Get User Address
export const USER_ADDRESS_GET_REQUEST = "USER_ADDRESS_GET_REQUEST";
export const USER_ADDRESS_GET_SUCCESS = "USER_ADDRESS_GET_SUCCESS";
export const USER_ADDRESS_GET_FAILURE = "USER_ADDRESS_GET_FAILURE";
//Get User Address
export const USER_ADDRESS_POST_REQUEST = "USER_ADDRESS_POST_REQUEST";
export const USER_ADDRESS_POST_SUCCESS = "USER_ADDRESS_POST_SUCCESS";
export const USER_ADDRESS_POST_FAILURE = "USER_ADDRESS_POST_FAILURE";
//User Address Update
export const USER_ADDRESS_UPDATE_REQUEST = "USER_ADDRESS_UPDATE_REQUEST";
export const USER_ADDRESS_UPDATE_SUCCESS = "USER_ADDRESS_UPDATE_SUCCESS";
export const USER_ADDRESS_UPDATE_FAILURE = "USER_ADDRESS_UPDATE_FAILURE";
